### ISSUE TITLE
Todo

### ISSUE THREAD

**Issue by rayzen2002** [rayzen2002/neil-league#1]
#TODO
- [x] Oauth com faceit
- [x] Conectar com a API do Opendota
- [x] Expandir a pagina de Jogadores, talvez com um banco de dados com arquivos extras ??
- [x] Arena
