### ISSUE TITLE
Oauth

### ISSUE THREAD

**Issue by rayzen2002** [rayzen2002/neil-league#4]
#TODO
- [x] Geting authorization code
- [x] Trading authroziation code for access token
- [x] Creating cookie with some of access token data
- [ ] Refreshing the access token
