### ISSUE TITLE
Jogos

### ISSUE THREAD

**Issue by rayzen2002** [rayzen2002/neil-league#7]
#TODO
- [x] Fetching matches from Faceit API
- [x] Using faceitURL to fetch players in the match and get their ids
- [x] Using player ids to call for each player and find his steam id
- [ ] Convert from steam64 to steam32
- [ ] - [ ] Convert from steam64 to steam32
